# Generated by Django 4.0.6 on 2022-07-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_group_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='group',
            name='homework',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='homework',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
